name: Deploy fe

on:
  push:
    branches: release-fe
  workflow_dispatch:
    inputs:
      ignoreWarnings:
        type: boolean
        description: Ignore warning during build

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install deps & Build fe
        if: github.event.inputs.ignoreWarnings
        run: |
          cd frontend
          yarn
          CI=false yarn build
          
      - name: Install deps & Build fe (trat warnings as errors)
        if: github.event.inputs.ignoreWarnings == false
        run: |
          cd frontend
          yarn
          CI=false yarn build
          
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: "github-views.com"
          username: "ubuntu"
          key: ${{ secrets.SERVER_SSH }}
          source: "frontend/build"
          target: "~/ghv-frontend"
