name: Deploy fe

on:
  push:
    branches: release-fe
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps & Build fe
        run: |
          cd frontend
          yarn
          yarn build
          
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: "github-views.com"
          username: "ubuntu"
          key: ${{ secrets.SERVER_SSH }}
          source: "frontend/build"
          target: "~/ghv-frontend"
